spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: ZB
  resources:
    static-locations: classpath:/static
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
server:
  edgex: localhost
  port: 8101
mq: activemq